Document: rave
Title: Debian rave Manual
Author: <insert document author here>
Abstract: This manual describes what rave is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rave/rave.sgml.gz

Format: postscript
Files: /usr/share/doc/rave/rave.ps.gz

Format: text
Files: /usr/share/doc/rave/rave.text.gz

Format: HTML
Index: /usr/share/doc/rave/html/index.html
Files: /usr/share/doc/rave/html/*.html

  
